### PR TITLE
added fixes

### PR DESCRIPTION
**Pull request by mul53**
PR Notes:
- [x] Fix Ethereum name typo
- [x] Add correct text for wrap functionality

### CODE REVIEW

**Comment by mul53** [comment]
hey @leonprou just a ping to let you know about this PR

**Review by leonprou — APPROVED** [review]

**Comment by IvanRF** [comment]
Thanks for fixing both reported issues! 👍

**Comment by IvanRF** [comment]
@mul53 the URL on add/remove liquidity pages is also using `ETH` instead of `FUSE`
For example:
https://beta.fuseswap.com/#/add/0x94Ba7A27c7A95863d1bdC7645AC2951E0cca06bA/ETH

**Comment by mul53** [comment]
Hey @IvanRF im aware of that, I will put in a fix over the course of the week thanks for the help on fuseswap

**Pull request merged**
